[terminal.shell]
program = "/bin/zsh"

[env]
TERM = "xterm-256color"

[window]
decorations = "Full"
dynamic_title = true
option_as_alt = "Both"
opacity = 1
blur = true

[window.dimensions]
columns = 160
lines = 80

[font]
size = 20

[font.bold]
family = "IosevkaTerm"
style = "Bold"

[font.italic]
family = "IosevkaTerm"
style = "Italic"

[font.normal]
family = "IosevkaTerm"
style = "Regular"

[font.offset]
x = 0
y = 0

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true

[bell]
animation = "EaseOutExpo"
duration = 0

[selection]
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>"

[cursor]
blink_interval = 500
blink_timeout = 5
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Underline"

[mouse]
hide_when_typing = true
bindings = [{ mouse = "Middle", action = "PasteSelection" }]

[keyboard]
bindings = [
  { key = "+", mods = "Control", action = "IncreaseFontSize" },
  { key = "-", mods = "Control", action = "DecreaseFontSize" },
  { key = "=", mods = "Control", action = "ResetFontSize" },
]

[general]
live_config_reload = true
import = ["~/.config/alacritty/themes/tokyo-night.toml"]
# import = ["~/.config/alacritty/themes/monokai.dark.toml"]

[terminal]
