import = [
  "~/.config/alacritty/themes/tokyo-night.toml"
]
live_config_reload = true

[shell]
program = "/bin/zsh"

[env]
TERM = "xterm-256color"

[window]
decorations = "full"
dynamic_title = true
option_as_alt = "Both"
opacity = 0.95
blur = true

[window.dimensions]
columns = 160
lines = 80

[window.padding]
x = 4
y = 4

[font]
# size = 16

[font.bold]
family = "iA Writer Mono S"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "iA Writer Mono S"

[font.normal]
family = "iA Writer Mono S"
style = "Regular"

[font.offset]
x = 0
y = 0

[colors]
draw_bold_text_with_bright_colors = true

[bell]
animation = "EaseOutExpo"
duration = 0

[selection]
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>"

[cursor]
blink_interval = 500
blink_timeout = 5
unfocused_hollow = false

[cursor.style]
blinking = "Off"
shape = "Block"

[mouse]
hide_when_typing = true
bindings = [
  { mouse = "Middle", action = "PasteSelection" }
]

[keyboard]
bindings = [
  { key = "+", mods = "Control", action = "IncreaseFontSize" },
  { key = "-", mods = "Control", action = "DecreaseFontSize" },
  # { key = "=", mods = "Control", action = "ResetFontSize" },
]
